apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ printf "%s-%s-%s-mongodb" $.Release.Namespace $.Release.Name "wekan-db" }}
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: registry-1.docker.io/bitnamicharts
    targetRevision: "16.4.0"
    chart: mongodb
    helm:
      valuesObject:
        global:
          defaultStorageClass: {{ $.Values.global.dbStorageClassName }}
        architecture: standalone
        useStatefulSet: false
        auth:
          rootPassword: "senha_root"
          usernames:
            - app_owner
          databases:
            - app_data
          existingSecret: kanban-kanban-chart-wekan-db-mongodb
          # passwords:
          #   - senha_app_owner
        resources:
          requests:
            cpu: 150m
            memory: 2Gi
          limits:
            cpu: 1
            memory: 2Gi
        persistence:
          size: 20Gi
        networkPolicy:
          enabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: kanban
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true
    - RespectIgnoreDifferences=true
    - ApplyOutOfSyncOnly=true
